### 1. Implementation of internal cross_entropy

convert logits to probabilitiesa

In [16]:
import torch
import torch.nn.functional as F

# Sample data
logits = torch.tensor([
    [2.0, 1.0, 0.1],  # Sample 1: raw scores for 3 classes
    [0.5, 3.0, 0.2],  # Sample 2: raw scores for 3 classes
])
targets = torch.tensor([0, 1])  # Correct classes: class 0 for sample 1, class 1 for sample 2

# Step 1: Softmax
probs = F.softmax(logits, dim=1)
print("Probabilities:")
print(probs)
# Output:
# tensor([[0.7311, 0.2689, 0.1225],  # Sample 1 probs (sum=1.0)
#         [0.1088, 0.7408, 0.0804]])  # Sample 2 probs (sum=1.0)

Probabilities:
tensor([[0.6590, 0.2424, 0.0986],
        [0.0718, 0.8750, 0.0532]])


select probabilities of correct classes

In [ ]:
selected_probs = probs[range(len(targets)), targets]

In [19]:
# Step 2: Pick correct class probabilities
print("Row indices:", list(range(len(targets))))  # [0, 1]
print("Column indices (targets):", targets.tolist())  # [0, 1]

selected_probs = probs[range(len(targets)), targets]
print("Selected probabilities:", selected_probs)
# Output: tensor([0.7311, 0.7408])
# Meaning:
# - Sample 1 had 65.90% probability for correct class 0
# - Sample 2 had 87.50% probability for correct class 1

Row indices: [0, 1]
Column indices (targets): [0, 1]
Selected probabilities: tensor([0.6590, 0.8750])


Compute negative log likelihood

In [20]:
loss_manual = -torch.log(selected_probs).mean()

In [21]:
# Step 3: Negative log likelihood
log_probs = torch.log(selected_probs)
print("Log probabilities:", log_probs)
# Output: tensor([-0.3133, -0.3001])

neg_log_probs = -log_probs
print("Negative log probabilities:", neg_log_probs)
# Output: tensor([0.3133, 0.3001])

loss_manual = neg_log_probs.mean()
print("Final loss:", loss_manual)

Log probabilities: tensor([-0.4170, -0.1336])
Negative log probabilities: tensor([0.4170, 0.1336])
Final loss: tensor(0.2753)


### multinomial

In [2]:
import torch

# Probability distribution over 5 tokens
probs = torch.tensor([[0.1, 0.2, 0.5, 0.15, 0.05]])  # Shape: (1, 5)

# Sample 10 times to see the randomness
for i in range(10):
    idx_next = torch.multinomial(probs, num_samples=1)
    print(f"Sample {i+1}: token {idx_next.item()}")

# Possible output:
# Sample 1: token 2  # Token 2 has 50% chance - most likely
# Sample 2: token 1  # Token 1 has 20% chance
# Sample 3: token 2  # Token 2 again (most probable)
# Sample 4: token 3  # Token 3 has 15% chance
# Sample 5: token 2  # Token 2 again
# ...

Sample 1: token 3
Sample 2: token 3
Sample 3: token 2
Sample 4: token 2
Sample 5: token 1
Sample 6: token 2
Sample 7: token 0
Sample 8: token 2
Sample 9: token 2
Sample 10: token 2


 other cases, and for that multinomial its better

In [6]:
idx_next = torch.argmax(probs, dim=-1, keepdim=True)  # Always picks highest prob
# Would always choose the same token → boring, repetitive text
idx_next

tensor([[2]])

In [11]:
idx_next = torch.multinomial(probs, num_samples=1)  # Random sampling
# Introduces creativity and variation in generation
idx_next

tensor([[0]])